In [ ]:
import torch
import numpy as np
import time

In [ ]:
# Matrix Multiplication

## Using NumPy

A_np = np.array([[78, 11, 56], [92, 67, 45], [8, 99, 71]])
B_np = np.array([[23, 78, 11], [14, 67, 45], [8, 34, 71]])

start = time.time()
C_np = A_np @ B_np
end = time.time()

print(f"NumPy time: {end - start:.4f} sec")

## Using PyTorch (CPU)

A_torch = torch.tensor([[78, 11, 56], [92, 67, 45], [8, 99, 71]], dtype=torch.float)
B_torch = torch.tensor([[23, 78, 11], [14, 67, 45], [8, 34, 71]], dtype=torch.float)

start = time.time()
C_torch = A_torch @ B_torch
end = time.time()

print(f"PyTorch time: {end - start:.4f} sec")


# Using PyTorch (GPU, if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
A_torch_gpu = A_torch.to(device)
B_torch_gpu = B_torch.to(device)
if device == "cuda":
    start = time.time()
    C_torch_gpu = torch.matmul(A_torch_gpu, B_torch_gpu)
    end = time.time()
    print(f"PyTorch (GPU) time: {end - start:.4f} sec")

NumPy time: 0.0002 sec
PyTorch time: 0.0002 sec
PyTorch (GPU) time: 0.0002 sec


### Time with CPU:
NumPy time: 0.0002 sec \
PyTorch time: 0.0454 sec

### Time with GPU:
NumPy time: 0.0001 sec \
PyTorch time: 0.0002 sec \
PyTorch (GPU) time: 0.0001 sec

In [ ]:
# Array Broadcasting

# Scalar and Array
a = np.array([1, 2, 3])
print(a.shape)
b = 2
print("Scalar and Array:")
c = a + b
print(c)
print("Output shape \n", c.shape)
print("---------------------------------")

# (m,1) + (1,n) -> (m,n)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
b = np.array([10, 20, 30])
print(b.shape)
print("Compatible Shapes:")
c = a + b
print(c)
print("Output shape \n", c.shape)
print("---------------------------------")

# (m,n) + (n,) -> (m,n)
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape)
b = np.array([[10, 20]])
print(b.shape)
print("Another Compatible Shape:")
c = a + b
print(c)
print("Output shape \n", c.shape)
print("---------------------------------")

(3,)
Scalar and Array:
[3 4 5]
Output shape 
 (3,)
---------------------------------
(2, 3)
(3,)
Compatible Shapes:
[[11 22 33]
 [14 25 36]]
Output shape 
 (2, 3)
---------------------------------
(3, 2)
(1, 2)
Another Compatible Shape:
[[11 22]
 [13 24]
 [15 26]]
Output shape 
 (3, 2)
---------------------------------


In [ ]:
## Here Broadcasting Fails

# Incompatible shapes
a = np.array([[1, 2], [3, 4]])
print(a.shape)
b = np.array([1, 2])
print(b.shape)
print("Incompatible Shapes - Fails:")
try:
    print(a + b)
except ValueError as e:
    print(f"Error: {e}")
print("---------------------------------")

# Another incompatible shape example
a = np.array([1, 2, 3])
print(a.shape)
b = np.array([[1], [2]])
print(b.shape)
print("Another Incompatible Shape - Fails:")
try:
    print(a + b)
except ValueError as e:
    print(f"Error: {e}")
print("---------------------------------")


(2, 2)
(2,)
Incompatible Shapes - Fails:
[[2 4]
 [4 6]]
---------------------------------
(3,)
(2, 1)
Another Incompatible Shape - Fails:
[[2 3 4]
 [3 4 5]]
---------------------------------


In [ ]:
## Conclusion is
# -> Works when dimensions are equal or one is 1 (Scalar).
# ->Fails otherwise.

In [ ]:
# Activation Function
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

def leaky_relu(x, alpha=0.01):
    return np.maximum(alpha * x, x)

def leaky_relu_derivative(x, alpha=0.01):
    dx = np.ones_like(x)
    dx[x < 0] = alpha
    return dx

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

In [ ]:
# Example Usage of Activation Functions

x = np.array([-2, -1, 0, 1, 2], dtype=float)
print(x)

print("ReLU:")
print("Output:", relu(x))
print("Derivative:", relu_derivative(x))
print("---------------------------------")

print("Sigmoid:")
print("Output:", sigmoid(x))
print("Derivative:", sigmoid_derivative(x))
print("---------------------------------")

print("Tanh:")
print("Output:", tanh(x))
print("Derivative:", tanh_derivative(x))
print("---------------------------------")

alpha_leaky = 0.1
print(f"Leaky ReLU (alpha={alpha_leaky}):")
print("Output:", leaky_relu(x, alpha=alpha_leaky))
print("Derivative:", leaky_relu_derivative(x, alpha=alpha_leaky))
print("---------------------------------")

x_new = np.array([1.0, 2.0, 3.0])
print("Softmax:")
print("Input:", x_new)
print("Output:", softmax(x_new))
print("---------------------------------")

[-2. -1.  0.  1.  2.]
ReLU:
Output: [0. 0. 0. 1. 2.]
Derivative: [0. 0. 0. 1. 1.]
---------------------------------
Sigmoid:
Output: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]
Derivative: [0.10499359 0.19661193 0.25       0.19661193 0.10499359]
---------------------------------
Tanh:
Output: [-0.96402758 -0.76159416  0.          0.76159416  0.96402758]
Derivative: [0.07065082 0.41997434 1.         0.41997434 0.07065082]
---------------------------------
Leaky ReLU (alpha=0.1):
Output: [-0.2 -0.1  0.   1.   2. ]
Derivative: [0.1 0.1 1.  1.  1. ]
---------------------------------
Softmax:
Input: [1. 2. 3.]
Output: [0.09003057 0.24472847 0.66524096]
---------------------------------
